version: '3.8'

services:
  api-v1-prod:
    build:
      context: .
      dockerfile: Dockerfile.api-v1-prod
    networks:
      - internal
    ports:
      - "8000" # This is only for internal use, not exposed to host

  exposed-service:
    build:
      context: .
      dockerfile: Dockerfile.exposed-service
    networks:
      - internal
      - external
    ports:
      - "8080:8080" # Expose this service to the host on port 8080

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
