# Dockerfile for api-v1-prod.local
FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Expose port and start the application
EXPOSE 8000
CMD [ "node", "index.js" ]
